### ISSUE TITLE
How to update prebuilts

### ISSUE THREAD

**Issue by Thomvis** [Mishkun/try-compose#2]
Thanks for the repo, it really helps with setting up a new project with compose support.

I noticed that some of the more recent changes to ASOP are not part of the prebuilt zip you so kindly provide. Would it be possible for you to share instructions on how to create the prebuilts from a up-to-date checkout of ASOP?

Thanks again!

**Comment by Mishkun** [comment]
If you have an up-to-date checkout of AOSP, you should be able to run
```
./gradlew createArchive
```
this will build the archives and install them to your maven local repo.

Anyways, thanks for reaching me out, I will update prebuilts soon ;)

**Comment by Mishkun** [comment]
@Thomvis I've published freshly-baked prebuilts and also updated an instruction about how to use own prebuilts. If you have any questions left, feel free to ask, or otherwise close the issue

**Comment by Thomvis** [comment]
Thank you!
